# set workflow to manual trigger
on: [workflow_dispatch]

name: CI-CD Bicep Demo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      name: 'Logging in to Azure'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # set as secret JSON object in repo

      # Deploy Bicep file
    - name: deploy bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: filesynctesting
        #region: westeurope # we need to set this on subscription scoped deployments
        template: ./Bicep/2.adv-parameters-functions/demo3.bicep
        deploymentName: 'gh-action-cd-demo'
        parameters: environment=prod
        failOnStdErr: false